# Generated by ariadne-codegen
# Source: ./documents

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteAllCategories(BaseModel):
    delete_all_categories: Optional[
        List[Optional["DeleteAllCategoriesDeleteAllCategories"]]
    ] = Field(alias="deleteAllCategories")


class DeleteAllCategoriesDeleteAllCategories(BaseModel):
    id: str
    state: EntityState


DeleteAllCategories.model_rebuild()
