# Generated by ariadne-codegen
# Source: ./documents

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteAllConversations(BaseModel):
    delete_all_conversations: Optional[
        list[Optional["DeleteAllConversationsDeleteAllConversations"]]
    ] = Field(alias="deleteAllConversations")


class DeleteAllConversationsDeleteAllConversations(BaseModel):
    id: str
    state: EntityState


DeleteAllConversations.model_rebuild()
