# Generated by ariadne-codegen
# Source: ./documents

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteAllMedicalProcedures(BaseModel):
    delete_all_medical_procedures: Optional[
        List[Optional["DeleteAllMedicalProceduresDeleteAllMedicalProcedures"]]
    ] = Field(alias="deleteAllMedicalProcedures")


class DeleteAllMedicalProceduresDeleteAllMedicalProcedures(BaseModel):
    id: str
    state: EntityState


DeleteAllMedicalProcedures.model_rebuild()
