# Generated by ariadne-codegen
# Source: ./documents

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteReplica(BaseModel):
    delete_replica: Optional["DeleteReplicaDeleteReplica"] = Field(
        alias="deleteReplica"
    )


class DeleteReplicaDeleteReplica(BaseModel):
    id: str
    state: EntityState


DeleteReplica.model_rebuild()
