# Generated by ariadne-codegen
# Source: ./documents

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteAllFeeds(BaseModel):
    delete_all_feeds: Optional[List[Optional["DeleteAllFeedsDeleteAllFeeds"]]] = Field(
        alias="deleteAllFeeds"
    )


class DeleteAllFeedsDeleteAllFeeds(BaseModel):
    id: str
    state: EntityState


DeleteAllFeeds.model_rebuild()
