# Generated by ariadne-codegen
# Source: ./documents

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteOrganizations(BaseModel):
    delete_organizations: Optional[
        list[Optional["DeleteOrganizationsDeleteOrganizations"]]
    ] = Field(alias="deleteOrganizations")


class DeleteOrganizationsDeleteOrganizations(BaseModel):
    id: str
    state: EntityState


DeleteOrganizations.model_rebuild()
