# Generated by ariadne-codegen
# Source: ./documents

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteAllFacts(BaseModel):
    delete_all_facts: Optional[List[Optional["DeleteAllFactsDeleteAllFacts"]]] = Field(
        alias="deleteAllFacts"
    )


class DeleteAllFactsDeleteAllFacts(BaseModel):
    id: str
    state: EntityState


DeleteAllFacts.model_rebuild()
