# Generated by ariadne-codegen
# Source: ./documents

from typing import List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class DeleteEvents(BaseModel):
    delete_events: Optional[List[Optional["DeleteEventsDeleteEvents"]]] = Field(
        alias="deleteEvents"
    )


class DeleteEventsDeleteEvents(BaseModel):
    id: str
    state: EntityState


DeleteEvents.model_rebuild()
