# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class GetMedicalIndication(BaseModel):
    medical_indication: Optional["GetMedicalIndicationMedicalIndication"] = Field(
        alias="medicalIndication"
    )


class GetMedicalIndicationMedicalIndication(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    owner: "GetMedicalIndicationMedicalIndicationOwner"
    state: EntityState
    alternate_names: Optional[List[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[List[Optional["GetMedicalIndicationMedicalIndicationFeeds"]]]


class GetMedicalIndicationMedicalIndicationOwner(BaseModel):
    id: str


class GetMedicalIndicationMedicalIndicationFeeds(BaseModel):
    id: str
    name: str


GetMedicalIndication.model_rebuild()
GetMedicalIndicationMedicalIndication.model_rebuild()
