# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ArcadeProviders,
    AuthenticationServiceTypes,
    ChannelServiceTypes,
    ConnectorTypes,
    EntityState,
    IntegrationServiceTypes,
    MCPServerTypes,
    OAuthProviders,
    UserTypes,
)


class GetUserByIdentifier(BaseModel):
    user_by_identifier: Optional["GetUserByIdentifierUserByIdentifier"] = Field(
        alias="userByIdentifier"
    )


class GetUserByIdentifierUserByIdentifier(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    relevance: Optional[float]
    owner: "GetUserByIdentifierUserByIdentifierOwner"
    state: EntityState
    type: Optional[UserTypes]
    identifier: str
    description: Optional[str]
    connectors: Optional[
        list[Optional["GetUserByIdentifierUserByIdentifierConnectors"]]
    ]
    personas: Optional[list[Optional["GetUserByIdentifierUserByIdentifierPersonas"]]]
    quota: Optional["GetUserByIdentifierUserByIdentifierQuota"]
    credits: Optional[Any]
    last_credits_date: Optional[Any] = Field(alias="lastCreditsDate")
    accumulated_credits: Optional[Any] = Field(alias="accumulatedCredits")


class GetUserByIdentifierUserByIdentifierOwner(BaseModel):
    id: str


class GetUserByIdentifierUserByIdentifierConnectors(BaseModel):
    id: str
    name: str
    state: EntityState
    type: Optional[ConnectorTypes]
    authentication: Optional[
        "GetUserByIdentifierUserByIdentifierConnectorsAuthentication"
    ]
    integration: Optional["GetUserByIdentifierUserByIdentifierConnectorsIntegration"]
    channel: Optional["GetUserByIdentifierUserByIdentifierConnectorsChannel"]


class GetUserByIdentifierUserByIdentifierConnectorsAuthentication(BaseModel):
    type: AuthenticationServiceTypes
    token: Optional[str]
    api_key: Optional[str] = Field(alias="apiKey")
    microsoft: Optional[
        "GetUserByIdentifierUserByIdentifierConnectorsAuthenticationMicrosoft"
    ]
    google: Optional[
        "GetUserByIdentifierUserByIdentifierConnectorsAuthenticationGoogle"
    ]
    oauth: Optional["GetUserByIdentifierUserByIdentifierConnectorsAuthenticationOauth"]
    arcade: Optional[
        "GetUserByIdentifierUserByIdentifierConnectorsAuthenticationArcade"
    ]


class GetUserByIdentifierUserByIdentifierConnectorsAuthenticationMicrosoft(BaseModel):
    tenant_id: str = Field(alias="tenantId")
    client_id: str = Field(alias="clientId")
    client_secret: str = Field(alias="clientSecret")


class GetUserByIdentifierUserByIdentifierConnectorsAuthenticationGoogle(BaseModel):
    client_id: str = Field(alias="clientId")
    client_secret: str = Field(alias="clientSecret")


class GetUserByIdentifierUserByIdentifierConnectorsAuthenticationOauth(BaseModel):
    provider: OAuthProviders
    client_id: str = Field(alias="clientId")
    client_secret: str = Field(alias="clientSecret")
    refresh_token: str = Field(alias="refreshToken")
    redirect_uri: Optional[str] = Field(alias="redirectUri")
    metadata: Optional[str]


class GetUserByIdentifierUserByIdentifierConnectorsAuthenticationArcade(BaseModel):
    authorization_id: str = Field(alias="authorizationId")
    provider: ArcadeProviders
    metadata: Optional[str]


class GetUserByIdentifierUserByIdentifierConnectorsIntegration(BaseModel):
    type: IntegrationServiceTypes
    uri: Optional[str]
    slack: Optional["GetUserByIdentifierUserByIdentifierConnectorsIntegrationSlack"]
    email: Optional["GetUserByIdentifierUserByIdentifierConnectorsIntegrationEmail"]
    twitter: Optional["GetUserByIdentifierUserByIdentifierConnectorsIntegrationTwitter"]
    mcp: Optional["GetUserByIdentifierUserByIdentifierConnectorsIntegrationMcp"]


class GetUserByIdentifierUserByIdentifierConnectorsIntegrationSlack(BaseModel):
    token: str
    channel: str


class GetUserByIdentifierUserByIdentifierConnectorsIntegrationEmail(BaseModel):
    from_: str = Field(alias="from")
    subject: str
    to: list[str]


class GetUserByIdentifierUserByIdentifierConnectorsIntegrationTwitter(BaseModel):
    consumer_key: str = Field(alias="consumerKey")
    consumer_secret: str = Field(alias="consumerSecret")
    access_token_key: str = Field(alias="accessTokenKey")
    access_token_secret: str = Field(alias="accessTokenSecret")


class GetUserByIdentifierUserByIdentifierConnectorsIntegrationMcp(BaseModel):
    token: Optional[str]
    type: MCPServerTypes


class GetUserByIdentifierUserByIdentifierConnectorsChannel(BaseModel):
    type: ChannelServiceTypes
    slack: Optional["GetUserByIdentifierUserByIdentifierConnectorsChannelSlack"]
    teams: Optional["GetUserByIdentifierUserByIdentifierConnectorsChannelTeams"]
    discord: Optional["GetUserByIdentifierUserByIdentifierConnectorsChannelDiscord"]


class GetUserByIdentifierUserByIdentifierConnectorsChannelSlack(BaseModel):
    bot_token: str = Field(alias="botToken")
    signing_secret: Optional[str] = Field(alias="signingSecret")
    app_id: Optional[str] = Field(alias="appId")


class GetUserByIdentifierUserByIdentifierConnectorsChannelTeams(BaseModel):
    bot_id: str = Field(alias="botId")
    bot_password: str = Field(alias="botPassword")
    tenant_id: Optional[str] = Field(alias="tenantId")


class GetUserByIdentifierUserByIdentifierConnectorsChannelDiscord(BaseModel):
    bot_token: str = Field(alias="botToken")
    application_id: Optional[str] = Field(alias="applicationId")
    public_key: Optional[str] = Field(alias="publicKey")


class GetUserByIdentifierUserByIdentifierPersonas(BaseModel):
    id: str
    name: str
    state: EntityState
    identifier: Optional[str]
    platform: Optional[str]
    display_name: Optional[str] = Field(alias="displayName")
    timezone: Optional[str]
    role: Optional[str]
    instructions: Optional[str]
    facts: Optional[list["GetUserByIdentifierUserByIdentifierPersonasFacts"]]


class GetUserByIdentifierUserByIdentifierPersonasFacts(BaseModel):
    id: Optional[str]
    text: Optional[str]


class GetUserByIdentifierUserByIdentifierQuota(BaseModel):
    credits: Optional[int]


GetUserByIdentifier.model_rebuild()
GetUserByIdentifierUserByIdentifier.model_rebuild()
GetUserByIdentifierUserByIdentifierConnectors.model_rebuild()
GetUserByIdentifierUserByIdentifierConnectorsAuthentication.model_rebuild()
GetUserByIdentifierUserByIdentifierConnectorsIntegration.model_rebuild()
GetUserByIdentifierUserByIdentifierConnectorsChannel.model_rebuild()
GetUserByIdentifierUserByIdentifierPersonas.model_rebuild()
