# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel


class GetMedicalGuideline(BaseModel):
    medical_guideline: Optional["GetMedicalGuidelineMedicalGuideline"] = Field(
        alias="medicalGuideline"
    )


class GetMedicalGuidelineMedicalGuideline(BaseModel):
    id: str
    name: str
    alternate_names: Optional[List[Optional[str]]] = Field(alias="alternateNames")
    creation_date: Any = Field(alias="creationDate")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    relevance: Optional[float]


GetMedicalGuideline.model_rebuild()
