# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState, LinkTypes


class GetMedicalDevice(BaseModel):
    medical_device: Optional["GetMedicalDeviceMedicalDevice"] = Field(
        alias="medicalDevice"
    )


class GetMedicalDeviceMedicalDevice(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    owner: "GetMedicalDeviceMedicalDeviceOwner"
    state: EntityState
    alternate_names: Optional[list[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[list[Optional["GetMedicalDeviceMedicalDeviceFeeds"]]]
    links: Optional[list[Optional["GetMedicalDeviceMedicalDeviceLinks"]]]
    workflow: Optional["GetMedicalDeviceMedicalDeviceWorkflow"]
    location: Optional["GetMedicalDeviceMedicalDeviceLocation"]
    h_3: Optional["GetMedicalDeviceMedicalDeviceH3"] = Field(alias="h3")


class GetMedicalDeviceMedicalDeviceOwner(BaseModel):
    id: str


class GetMedicalDeviceMedicalDeviceFeeds(BaseModel):
    id: str
    name: str


class GetMedicalDeviceMedicalDeviceLinks(BaseModel):
    uri: Optional[Any]
    link_type: Optional[LinkTypes] = Field(alias="linkType")
    excerpts: Optional[str]


class GetMedicalDeviceMedicalDeviceWorkflow(BaseModel):
    id: str
    name: str


class GetMedicalDeviceMedicalDeviceLocation(BaseModel):
    latitude: Optional[float]
    longitude: Optional[float]


class GetMedicalDeviceMedicalDeviceH3(BaseModel):
    h_3_r_0: Optional[str] = Field(alias="h3r0")
    h_3_r_1: Optional[str] = Field(alias="h3r1")
    h_3_r_2: Optional[str] = Field(alias="h3r2")
    h_3_r_3: Optional[str] = Field(alias="h3r3")
    h_3_r_4: Optional[str] = Field(alias="h3r4")
    h_3_r_5: Optional[str] = Field(alias="h3r5")
    h_3_r_6: Optional[str] = Field(alias="h3r6")
    h_3_r_7: Optional[str] = Field(alias="h3r7")
    h_3_r_8: Optional[str] = Field(alias="h3r8")
    h_3_r_9: Optional[str] = Field(alias="h3r9")
    h_3_r_10: Optional[str] = Field(alias="h3r10")
    h_3_r_11: Optional[str] = Field(alias="h3r11")
    h_3_r_12: Optional[str] = Field(alias="h3r12")
    h_3_r_13: Optional[str] = Field(alias="h3r13")
    h_3_r_14: Optional[str] = Field(alias="h3r14")
    h_3_r_15: Optional[str] = Field(alias="h3r15")


GetMedicalDevice.model_rebuild()
GetMedicalDeviceMedicalDevice.model_rebuild()
