# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class GetMedicalDevice(BaseModel):
    medical_device: Optional["GetMedicalDeviceMedicalDevice"] = Field(
        alias="medicalDevice"
    )


class GetMedicalDeviceMedicalDevice(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    owner: "GetMedicalDeviceMedicalDeviceOwner"
    state: EntityState
    alternate_names: Optional[List[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[List[Optional["GetMedicalDeviceMedicalDeviceFeeds"]]]


class GetMedicalDeviceMedicalDeviceOwner(BaseModel):
    id: str


class GetMedicalDeviceMedicalDeviceFeeds(BaseModel):
    id: str
    name: str


GetMedicalDevice.model_rebuild()
GetMedicalDeviceMedicalDevice.model_rebuild()
