# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState, LinkTypes


class GetOrganization(BaseModel):
    organization: Optional["GetOrganizationOrganization"]


class GetOrganizationOrganization(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    owner: "GetOrganizationOrganizationOwner"
    state: EntityState
    alternate_names: Optional[list[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[list[Optional["GetOrganizationOrganizationFeeds"]]]
    links: Optional[list[Optional["GetOrganizationOrganizationLinks"]]]
    workflow: Optional["GetOrganizationOrganizationWorkflow"]
    location: Optional["GetOrganizationOrganizationLocation"]
    h_3: Optional["GetOrganizationOrganizationH3"] = Field(alias="h3")
    address: Optional["GetOrganizationOrganizationAddress"]
    founding_date: Optional[Any] = Field(alias="foundingDate")
    email: Optional[str]
    telephone: Optional[str]
    legal_name: Optional[str] = Field(alias="legalName")
    industries: Optional[list[Optional[str]]]
    revenue: Optional[Any]
    revenue_currency: Optional[str] = Field(alias="revenueCurrency")
    investment: Optional[Any]
    investment_currency: Optional[str] = Field(alias="investmentCurrency")
    founders: Optional[list[Optional["GetOrganizationOrganizationFounders"]]]
    employees: Optional[list[Optional["GetOrganizationOrganizationEmployees"]]]
    members: Optional[list[Optional["GetOrganizationOrganizationMembers"]]]
    parent_organization: Optional["GetOrganizationOrganizationParentOrganization"] = (
        Field(alias="parentOrganization")
    )
    member_of: Optional[list[Optional["GetOrganizationOrganizationMemberOf"]]] = Field(
        alias="memberOf"
    )
    sub_organizations: Optional[
        list[Optional["GetOrganizationOrganizationSubOrganizations"]]
    ] = Field(alias="subOrganizations")
    locations: Optional[list[Optional["GetOrganizationOrganizationLocations"]]]
    investments_received: Optional[
        list[Optional["GetOrganizationOrganizationInvestmentsReceived"]]
    ] = Field(alias="investmentsReceived")
    investor_funds: Optional[
        list[Optional["GetOrganizationOrganizationInvestorFunds"]]
    ] = Field(alias="investorFunds")


class GetOrganizationOrganizationOwner(BaseModel):
    id: str


class GetOrganizationOrganizationFeeds(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationLinks(BaseModel):
    uri: Optional[Any]
    link_type: Optional[LinkTypes] = Field(alias="linkType")
    excerpts: Optional[str]


class GetOrganizationOrganizationWorkflow(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationLocation(BaseModel):
    latitude: Optional[float]
    longitude: Optional[float]


class GetOrganizationOrganizationH3(BaseModel):
    h_3_r_0: Optional[str] = Field(alias="h3r0")
    h_3_r_1: Optional[str] = Field(alias="h3r1")
    h_3_r_2: Optional[str] = Field(alias="h3r2")
    h_3_r_3: Optional[str] = Field(alias="h3r3")
    h_3_r_4: Optional[str] = Field(alias="h3r4")
    h_3_r_5: Optional[str] = Field(alias="h3r5")
    h_3_r_6: Optional[str] = Field(alias="h3r6")
    h_3_r_7: Optional[str] = Field(alias="h3r7")
    h_3_r_8: Optional[str] = Field(alias="h3r8")
    h_3_r_9: Optional[str] = Field(alias="h3r9")
    h_3_r_10: Optional[str] = Field(alias="h3r10")
    h_3_r_11: Optional[str] = Field(alias="h3r11")
    h_3_r_12: Optional[str] = Field(alias="h3r12")
    h_3_r_13: Optional[str] = Field(alias="h3r13")
    h_3_r_14: Optional[str] = Field(alias="h3r14")
    h_3_r_15: Optional[str] = Field(alias="h3r15")


class GetOrganizationOrganizationAddress(BaseModel):
    street_address: Optional[str] = Field(alias="streetAddress")
    city: Optional[str]
    region: Optional[str]
    country: Optional[str]
    postal_code: Optional[str] = Field(alias="postalCode")


class GetOrganizationOrganizationFounders(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationEmployees(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationMembers(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationParentOrganization(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationMemberOf(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationSubOrganizations(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationLocations(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationInvestmentsReceived(BaseModel):
    id: str
    name: str


class GetOrganizationOrganizationInvestorFunds(BaseModel):
    id: str
    name: str


GetOrganization.model_rebuild()
GetOrganizationOrganization.model_rebuild()
