# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    AssemblyAIModels,
    AzureDocumentIntelligenceModels,
    AzureDocumentIntelligenceVersions,
    ContentClassificationServiceTypes,
    ContentIndexingServiceTypes,
    ContentTypes,
    DeepgramModels,
    ElevenLabsScribeModels,
    EmbeddingTypes,
    EntityEnrichmentServiceTypes,
    EntityExtractionServiceTypes,
    EntityResolutionStrategyTypes,
    EntityState,
    ExtractionTypes,
    FilePreparationServiceTypes,
    FileTypes,
    IntegrationServiceTypes,
    LinkTypes,
    MCPServerTypes,
    ObservableTypes,
    ParallelProcessors,
    ReductoEnrichmentModes,
    ReductoExtractionModes,
    ReductoOcrModes,
    ReductoOcrSystems,
    RegexSourceTypes,
    StorageGateRejectionActions,
    StorageGateTypes,
    StoragePolicyTypes,
    SummarizationTypes,
)


class GetWorkflow(BaseModel):
    workflow: Optional["GetWorkflowWorkflow"]


class GetWorkflowWorkflow(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    owner: "GetWorkflowWorkflowOwner"
    state: EntityState
    ingestion: Optional["GetWorkflowWorkflowIngestion"]
    indexing: Optional["GetWorkflowWorkflowIndexing"]
    preparation: Optional["GetWorkflowWorkflowPreparation"]
    extraction: Optional["GetWorkflowWorkflowExtraction"]
    classification: Optional["GetWorkflowWorkflowClassification"]
    enrichment: Optional["GetWorkflowWorkflowEnrichment"]
    storage: Optional["GetWorkflowWorkflowStorage"]
    actions: Optional[list[Optional["GetWorkflowWorkflowActions"]]]


class GetWorkflowWorkflowOwner(BaseModel):
    id: str


class GetWorkflowWorkflowIngestion(BaseModel):
    if_: Optional["GetWorkflowWorkflowIngestionIf"] = Field(alias="if")
    collections: Optional[list[Optional["GetWorkflowWorkflowIngestionCollections"]]]
    observations: Optional[list[Optional["GetWorkflowWorkflowIngestionObservations"]]]
    enable_email_collections: Optional[bool] = Field(alias="enableEmailCollections")
    enable_folder_collections: Optional[bool] = Field(alias="enableFolderCollections")
    enable_message_collections: Optional[bool] = Field(alias="enableMessageCollections")


class GetWorkflowWorkflowIngestionIf(BaseModel):
    types: Optional[list[ContentTypes]]
    file_types: Optional[list[FileTypes]] = Field(alias="fileTypes")
    formats: Optional[list[Optional[str]]]
    file_extensions: Optional[list[str]] = Field(alias="fileExtensions")
    allowed_paths: Optional[list[str]] = Field(alias="allowedPaths")
    excluded_paths: Optional[list[str]] = Field(alias="excludedPaths")


class GetWorkflowWorkflowIngestionCollections(BaseModel):
    id: str


class GetWorkflowWorkflowIngestionObservations(BaseModel):
    type: ObservableTypes
    observable: "GetWorkflowWorkflowIngestionObservationsObservable"


class GetWorkflowWorkflowIngestionObservationsObservable(BaseModel):
    id: str
    name: Optional[str]


class GetWorkflowWorkflowIndexing(BaseModel):
    jobs: Optional[list[Optional["GetWorkflowWorkflowIndexingJobs"]]]


class GetWorkflowWorkflowIndexingJobs(BaseModel):
    connector: Optional["GetWorkflowWorkflowIndexingJobsConnector"]


class GetWorkflowWorkflowIndexingJobsConnector(BaseModel):
    type: Optional[ContentIndexingServiceTypes]
    content_type: Optional[ContentTypes] = Field(alias="contentType")
    file_type: Optional[FileTypes] = Field(alias="fileType")


class GetWorkflowWorkflowPreparation(BaseModel):
    enable_unblocked_capture: Optional[bool] = Field(alias="enableUnblockedCapture")
    disable_smart_capture: Optional[bool] = Field(alias="disableSmartCapture")
    summarizations: Optional[
        list[Optional["GetWorkflowWorkflowPreparationSummarizations"]]
    ]
    jobs: Optional[list[Optional["GetWorkflowWorkflowPreparationJobs"]]]


class GetWorkflowWorkflowPreparationSummarizations(BaseModel):
    type: SummarizationTypes
    specification: Optional["GetWorkflowWorkflowPreparationSummarizationsSpecification"]
    tokens: Optional[int]
    items: Optional[int]
    prompt: Optional[str]


class GetWorkflowWorkflowPreparationSummarizationsSpecification(BaseModel):
    id: str


class GetWorkflowWorkflowPreparationJobs(BaseModel):
    connector: Optional["GetWorkflowWorkflowPreparationJobsConnector"]


class GetWorkflowWorkflowPreparationJobsConnector(BaseModel):
    type: FilePreparationServiceTypes
    file_types: Optional[list[FileTypes]] = Field(alias="fileTypes")
    azure_document: Optional[
        "GetWorkflowWorkflowPreparationJobsConnectorAzureDocument"
    ] = Field(alias="azureDocument")
    deepgram: Optional["GetWorkflowWorkflowPreparationJobsConnectorDeepgram"]
    assembly_ai: Optional["GetWorkflowWorkflowPreparationJobsConnectorAssemblyAi"] = (
        Field(alias="assemblyAI")
    )
    eleven_labs_scribe: Optional[
        "GetWorkflowWorkflowPreparationJobsConnectorElevenLabsScribe"
    ] = Field(alias="elevenLabsScribe")
    page: Optional["GetWorkflowWorkflowPreparationJobsConnectorPage"]
    document: Optional["GetWorkflowWorkflowPreparationJobsConnectorDocument"]
    email: Optional["GetWorkflowWorkflowPreparationJobsConnectorEmail"]
    model_document: Optional[
        "GetWorkflowWorkflowPreparationJobsConnectorModelDocument"
    ] = Field(alias="modelDocument")
    reducto: Optional["GetWorkflowWorkflowPreparationJobsConnectorReducto"]
    mistral: Optional["GetWorkflowWorkflowPreparationJobsConnectorMistral"]


class GetWorkflowWorkflowPreparationJobsConnectorAzureDocument(BaseModel):
    version: Optional[AzureDocumentIntelligenceVersions]
    model: Optional[AzureDocumentIntelligenceModels]
    endpoint: Optional[Any]
    key: Optional[str]


class GetWorkflowWorkflowPreparationJobsConnectorDeepgram(BaseModel):
    model: Optional[DeepgramModels]
    key: Optional[str]
    enable_redaction: Optional[bool] = Field(alias="enableRedaction")
    enable_speaker_diarization: Optional[bool] = Field(alias="enableSpeakerDiarization")
    detect_language: Optional[bool] = Field(alias="detectLanguage")
    language: Optional[str]


class GetWorkflowWorkflowPreparationJobsConnectorAssemblyAi(BaseModel):
    model: Optional[AssemblyAIModels]
    key: Optional[str]
    enable_redaction: Optional[bool] = Field(alias="enableRedaction")
    enable_speaker_diarization: Optional[bool] = Field(alias="enableSpeakerDiarization")
    detect_language: Optional[bool] = Field(alias="detectLanguage")
    language: Optional[str]


class GetWorkflowWorkflowPreparationJobsConnectorElevenLabsScribe(BaseModel):
    model: Optional[ElevenLabsScribeModels]
    key: Optional[str]
    enable_speaker_diarization: Optional[bool] = Field(alias="enableSpeakerDiarization")
    detect_language: Optional[bool] = Field(alias="detectLanguage")
    language: Optional[str]
    tag_audio_events: Optional[bool] = Field(alias="tagAudioEvents")


class GetWorkflowWorkflowPreparationJobsConnectorPage(BaseModel):
    enable_screenshot: Optional[bool] = Field(alias="enableScreenshot")


class GetWorkflowWorkflowPreparationJobsConnectorDocument(BaseModel):
    include_images: Optional[bool] = Field(alias="includeImages")


class GetWorkflowWorkflowPreparationJobsConnectorEmail(BaseModel):
    include_attachments: Optional[bool] = Field(alias="includeAttachments")


class GetWorkflowWorkflowPreparationJobsConnectorModelDocument(BaseModel):
    specification: Optional[
        "GetWorkflowWorkflowPreparationJobsConnectorModelDocumentSpecification"
    ]


class GetWorkflowWorkflowPreparationJobsConnectorModelDocumentSpecification(BaseModel):
    id: str


class GetWorkflowWorkflowPreparationJobsConnectorReducto(BaseModel):
    ocr_mode: Optional[ReductoOcrModes] = Field(alias="ocrMode")
    ocr_system: Optional[ReductoOcrSystems] = Field(alias="ocrSystem")
    extraction_mode: Optional[ReductoExtractionModes] = Field(alias="extractionMode")
    enable_enrichment: Optional[bool] = Field(alias="enableEnrichment")
    enrichment_mode: Optional[ReductoEnrichmentModes] = Field(alias="enrichmentMode")
    key: Optional[str]


class GetWorkflowWorkflowPreparationJobsConnectorMistral(BaseModel):
    key: Optional[str]


class GetWorkflowWorkflowExtraction(BaseModel):
    jobs: Optional[list[Optional["GetWorkflowWorkflowExtractionJobs"]]]


class GetWorkflowWorkflowExtractionJobs(BaseModel):
    connector: Optional["GetWorkflowWorkflowExtractionJobsConnector"]


class GetWorkflowWorkflowExtractionJobsConnector(BaseModel):
    type: EntityExtractionServiceTypes
    content_types: Optional[list[ContentTypes]] = Field(alias="contentTypes")
    file_types: Optional[list[FileTypes]] = Field(alias="fileTypes")
    extracted_types: Optional[list[ObservableTypes]] = Field(alias="extractedTypes")
    extracted_count: Optional[int] = Field(alias="extractedCount")
    azure_text: Optional["GetWorkflowWorkflowExtractionJobsConnectorAzureText"] = Field(
        alias="azureText"
    )
    azure_image: Optional["GetWorkflowWorkflowExtractionJobsConnectorAzureImage"] = (
        Field(alias="azureImage")
    )
    model_image: Optional["GetWorkflowWorkflowExtractionJobsConnectorModelImage"] = (
        Field(alias="modelImage")
    )
    model_text: Optional["GetWorkflowWorkflowExtractionJobsConnectorModelText"] = Field(
        alias="modelText"
    )


class GetWorkflowWorkflowExtractionJobsConnectorAzureText(BaseModel):
    confidence_threshold: Optional[float] = Field(alias="confidenceThreshold")
    enable_pii: Optional[bool] = Field(alias="enablePII")


class GetWorkflowWorkflowExtractionJobsConnectorAzureImage(BaseModel):
    confidence_threshold: Optional[float] = Field(alias="confidenceThreshold")


class GetWorkflowWorkflowExtractionJobsConnectorModelImage(BaseModel):
    specification: Optional[
        "GetWorkflowWorkflowExtractionJobsConnectorModelImageSpecification"
    ]


class GetWorkflowWorkflowExtractionJobsConnectorModelImageSpecification(BaseModel):
    id: str


class GetWorkflowWorkflowExtractionJobsConnectorModelText(BaseModel):
    specification: Optional[
        "GetWorkflowWorkflowExtractionJobsConnectorModelTextSpecification"
    ]
    token_threshold: Optional[int] = Field(alias="tokenThreshold")
    time_budget: Optional[Any] = Field(alias="timeBudget")
    entity_budget: Optional[int] = Field(alias="entityBudget")
    extraction_type: Optional[ExtractionTypes] = Field(alias="extractionType")


class GetWorkflowWorkflowExtractionJobsConnectorModelTextSpecification(BaseModel):
    id: str


class GetWorkflowWorkflowClassification(BaseModel):
    jobs: Optional[list[Optional["GetWorkflowWorkflowClassificationJobs"]]]


class GetWorkflowWorkflowClassificationJobs(BaseModel):
    connector: Optional["GetWorkflowWorkflowClassificationJobsConnector"]


class GetWorkflowWorkflowClassificationJobsConnector(BaseModel):
    type: ContentClassificationServiceTypes
    content_type: Optional[ContentTypes] = Field(alias="contentType")
    file_type: Optional[FileTypes] = Field(alias="fileType")
    model: Optional["GetWorkflowWorkflowClassificationJobsConnectorModel"]
    regex: Optional["GetWorkflowWorkflowClassificationJobsConnectorRegex"]


class GetWorkflowWorkflowClassificationJobsConnectorModel(BaseModel):
    specification: Optional[
        "GetWorkflowWorkflowClassificationJobsConnectorModelSpecification"
    ]
    rules: Optional[
        list[Optional["GetWorkflowWorkflowClassificationJobsConnectorModelRules"]]
    ]


class GetWorkflowWorkflowClassificationJobsConnectorModelSpecification(BaseModel):
    id: str


class GetWorkflowWorkflowClassificationJobsConnectorModelRules(BaseModel):
    then: Optional[str]
    if_: Optional[str] = Field(alias="if")


class GetWorkflowWorkflowClassificationJobsConnectorRegex(BaseModel):
    rules: Optional[
        list[Optional["GetWorkflowWorkflowClassificationJobsConnectorRegexRules"]]
    ]


class GetWorkflowWorkflowClassificationJobsConnectorRegexRules(BaseModel):
    then: Optional[str]
    type: Optional[RegexSourceTypes]
    path: Optional[str]
    matches: Optional[str]


class GetWorkflowWorkflowEnrichment(BaseModel):
    link: Optional["GetWorkflowWorkflowEnrichmentLink"]
    jobs: Optional[list[Optional["GetWorkflowWorkflowEnrichmentJobs"]]]
    entity_resolution: Optional["GetWorkflowWorkflowEnrichmentEntityResolution"] = (
        Field(alias="entityResolution")
    )


class GetWorkflowWorkflowEnrichmentLink(BaseModel):
    enable_crawling: Optional[bool] = Field(alias="enableCrawling")
    allowed_domains: Optional[list[str]] = Field(alias="allowedDomains")
    excluded_domains: Optional[list[str]] = Field(alias="excludedDomains")
    allowed_paths: Optional[list[str]] = Field(alias="allowedPaths")
    excluded_paths: Optional[list[str]] = Field(alias="excludedPaths")
    allowed_links: Optional[list[LinkTypes]] = Field(alias="allowedLinks")
    excluded_links: Optional[list[LinkTypes]] = Field(alias="excludedLinks")
    allowed_files: Optional[list[FileTypes]] = Field(alias="allowedFiles")
    excluded_files: Optional[list[FileTypes]] = Field(alias="excludedFiles")
    allowed_content_types: Optional[list[ContentTypes]] = Field(
        alias="allowedContentTypes"
    )
    excluded_content_types: Optional[list[ContentTypes]] = Field(
        alias="excludedContentTypes"
    )
    allow_content_domain: Optional[bool] = Field(alias="allowContentDomain")
    maximum_links: Optional[int] = Field(alias="maximumLinks")


class GetWorkflowWorkflowEnrichmentJobs(BaseModel):
    connector: Optional["GetWorkflowWorkflowEnrichmentJobsConnector"]


class GetWorkflowWorkflowEnrichmentJobsConnector(BaseModel):
    type: Optional[EntityEnrichmentServiceTypes]
    enriched_types: Optional[list[ObservableTypes]] = Field(alias="enrichedTypes")
    fhir: Optional["GetWorkflowWorkflowEnrichmentJobsConnectorFhir"]
    diffbot: Optional["GetWorkflowWorkflowEnrichmentJobsConnectorDiffbot"]
    parallel: Optional["GetWorkflowWorkflowEnrichmentJobsConnectorParallel"]


class GetWorkflowWorkflowEnrichmentJobsConnectorFhir(BaseModel):
    endpoint: Optional[Any]


class GetWorkflowWorkflowEnrichmentJobsConnectorDiffbot(BaseModel):
    key: Optional[Any]


class GetWorkflowWorkflowEnrichmentJobsConnectorParallel(BaseModel):
    processor: Optional[ParallelProcessors]
    is_synchronous: Optional[bool] = Field(alias="isSynchronous")


class GetWorkflowWorkflowEnrichmentEntityResolution(BaseModel):
    strategy: Optional[EntityResolutionStrategyTypes]
    threshold: Optional[float]
    specification: Optional[
        "GetWorkflowWorkflowEnrichmentEntityResolutionSpecification"
    ]


class GetWorkflowWorkflowEnrichmentEntityResolutionSpecification(BaseModel):
    id: str


class GetWorkflowWorkflowStorage(BaseModel):
    policy: Optional["GetWorkflowWorkflowStoragePolicy"]
    gate: Optional["GetWorkflowWorkflowStorageGate"]


class GetWorkflowWorkflowStoragePolicy(BaseModel):
    type: Optional[StoragePolicyTypes]
    allow_duplicates: Optional[bool] = Field(alias="allowDuplicates")
    embedding_types: Optional[list[EmbeddingTypes]] = Field(alias="embeddingTypes")
    enable_snapshots: Optional[bool] = Field(alias="enableSnapshots")
    snapshot_count: Optional[int] = Field(alias="snapshotCount")


class GetWorkflowWorkflowStorageGate(BaseModel):
    type: StorageGateTypes
    specification: Optional["GetWorkflowWorkflowStorageGateSpecification"]
    rules: Optional[list["GetWorkflowWorkflowStorageGateRules"]]
    uri: Optional[Any]
    on_reject: Optional[StorageGateRejectionActions] = Field(alias="onReject")


class GetWorkflowWorkflowStorageGateSpecification(BaseModel):
    id: str


class GetWorkflowWorkflowStorageGateRules(BaseModel):
    if_: str = Field(alias="if")


class GetWorkflowWorkflowActions(BaseModel):
    connector: Optional["GetWorkflowWorkflowActionsConnector"]


class GetWorkflowWorkflowActionsConnector(BaseModel):
    type: IntegrationServiceTypes
    uri: Optional[str]
    slack: Optional["GetWorkflowWorkflowActionsConnectorSlack"]
    email: Optional["GetWorkflowWorkflowActionsConnectorEmail"]
    twitter: Optional["GetWorkflowWorkflowActionsConnectorTwitter"]
    mcp: Optional["GetWorkflowWorkflowActionsConnectorMcp"]


class GetWorkflowWorkflowActionsConnectorSlack(BaseModel):
    token: str
    channel: str


class GetWorkflowWorkflowActionsConnectorEmail(BaseModel):
    from_: str = Field(alias="from")
    subject: str
    to: list[str]


class GetWorkflowWorkflowActionsConnectorTwitter(BaseModel):
    consumer_key: str = Field(alias="consumerKey")
    consumer_secret: str = Field(alias="consumerSecret")
    access_token_key: str = Field(alias="accessTokenKey")
    access_token_secret: str = Field(alias="accessTokenSecret")


class GetWorkflowWorkflowActionsConnectorMcp(BaseModel):
    token: Optional[str]
    type: MCPServerTypes


GetWorkflow.model_rebuild()
GetWorkflowWorkflow.model_rebuild()
GetWorkflowWorkflowIngestion.model_rebuild()
GetWorkflowWorkflowIngestionObservations.model_rebuild()
GetWorkflowWorkflowIndexing.model_rebuild()
GetWorkflowWorkflowIndexingJobs.model_rebuild()
GetWorkflowWorkflowPreparation.model_rebuild()
GetWorkflowWorkflowPreparationSummarizations.model_rebuild()
GetWorkflowWorkflowPreparationJobs.model_rebuild()
GetWorkflowWorkflowPreparationJobsConnector.model_rebuild()
GetWorkflowWorkflowPreparationJobsConnectorModelDocument.model_rebuild()
GetWorkflowWorkflowExtraction.model_rebuild()
GetWorkflowWorkflowExtractionJobs.model_rebuild()
GetWorkflowWorkflowExtractionJobsConnector.model_rebuild()
GetWorkflowWorkflowExtractionJobsConnectorModelImage.model_rebuild()
GetWorkflowWorkflowExtractionJobsConnectorModelText.model_rebuild()
GetWorkflowWorkflowClassification.model_rebuild()
GetWorkflowWorkflowClassificationJobs.model_rebuild()
GetWorkflowWorkflowClassificationJobsConnector.model_rebuild()
GetWorkflowWorkflowClassificationJobsConnectorModel.model_rebuild()
GetWorkflowWorkflowClassificationJobsConnectorRegex.model_rebuild()
GetWorkflowWorkflowEnrichment.model_rebuild()
GetWorkflowWorkflowEnrichmentJobs.model_rebuild()
GetWorkflowWorkflowEnrichmentJobsConnector.model_rebuild()
GetWorkflowWorkflowEnrichmentEntityResolution.model_rebuild()
GetWorkflowWorkflowStorage.model_rebuild()
GetWorkflowWorkflowStorageGate.model_rebuild()
GetWorkflowWorkflowActions.model_rebuild()
GetWorkflowWorkflowActionsConnector.model_rebuild()
