# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import ContentTypes, EntityState, FileTypes


class IngestEncodedFile(BaseModel):
    ingest_encoded_file: Optional["IngestEncodedFileIngestEncodedFile"] = Field(
        alias="ingestEncodedFile"
    )


class IngestEncodedFileIngestEncodedFile(BaseModel):
    id: str
    name: str
    state: EntityState
    type: Optional[ContentTypes]
    file_type: Optional[FileTypes] = Field(alias="fileType")
    mime_type: Optional[str] = Field(alias="mimeType")
    uri: Optional[Any]
    collections: Optional[
        List[Optional["IngestEncodedFileIngestEncodedFileCollections"]]
    ]


class IngestEncodedFileIngestEncodedFileCollections(BaseModel):
    id: str
    name: str


IngestEncodedFile.model_rebuild()
IngestEncodedFileIngestEncodedFile.model_rebuild()
