# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState


class QueryMedicalTherapies(BaseModel):
    medical_therapies: Optional["QueryMedicalTherapiesMedicalTherapies"] = Field(
        alias="medicalTherapies"
    )


class QueryMedicalTherapiesMedicalTherapies(BaseModel):
    results: Optional[List[Optional["QueryMedicalTherapiesMedicalTherapiesResults"]]]


class QueryMedicalTherapiesMedicalTherapiesResults(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    relevance: Optional[float]
    owner: "QueryMedicalTherapiesMedicalTherapiesResultsOwner"
    state: EntityState
    alternate_names: Optional[List[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[List[Optional["QueryMedicalTherapiesMedicalTherapiesResultsFeeds"]]]


class QueryMedicalTherapiesMedicalTherapiesResultsOwner(BaseModel):
    id: str


class QueryMedicalTherapiesMedicalTherapiesResultsFeeds(BaseModel):
    id: str
    name: str


QueryMedicalTherapies.model_rebuild()
QueryMedicalTherapiesMedicalTherapies.model_rebuild()
QueryMedicalTherapiesMedicalTherapiesResults.model_rebuild()
