# Generated by ariadne-codegen
# Source: ./documents

from typing import List, Optional

from .base_model import BaseModel


class QueryLabels(BaseModel):
    labels: Optional["QueryLabelsLabels"]


class QueryLabelsLabels(BaseModel):
    results: Optional[List[Optional["QueryLabelsLabelsResults"]]]


class QueryLabelsLabelsResults(BaseModel):
    id: str
    name: str


QueryLabels.model_rebuild()
QueryLabelsLabels.model_rebuild()
