# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState, LinkTypes


class QueryMedicalConditionsClusters(BaseModel):
    medical_conditions: Optional["QueryMedicalConditionsClustersMedicalConditions"] = (
        Field(alias="medicalConditions")
    )


class QueryMedicalConditionsClustersMedicalConditions(BaseModel):
    results: Optional[
        list[Optional["QueryMedicalConditionsClustersMedicalConditionsResults"]]
    ]
    clusters: Optional["QueryMedicalConditionsClustersMedicalConditionsClusters"]


class QueryMedicalConditionsClustersMedicalConditionsResults(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    relevance: Optional[float]
    owner: "QueryMedicalConditionsClustersMedicalConditionsResultsOwner"
    state: EntityState
    alternate_names: Optional[list[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[
        list[Optional["QueryMedicalConditionsClustersMedicalConditionsResultsFeeds"]]
    ]
    links: Optional[
        list[Optional["QueryMedicalConditionsClustersMedicalConditionsResultsLinks"]]
    ]
    workflow: Optional["QueryMedicalConditionsClustersMedicalConditionsResultsWorkflow"]
    location: Optional["QueryMedicalConditionsClustersMedicalConditionsResultsLocation"]
    h_3: Optional["QueryMedicalConditionsClustersMedicalConditionsResultsH3"] = Field(
        alias="h3"
    )


class QueryMedicalConditionsClustersMedicalConditionsResultsOwner(BaseModel):
    id: str


class QueryMedicalConditionsClustersMedicalConditionsResultsFeeds(BaseModel):
    id: str
    name: str


class QueryMedicalConditionsClustersMedicalConditionsResultsLinks(BaseModel):
    uri: Optional[Any]
    link_type: Optional[LinkTypes] = Field(alias="linkType")
    excerpts: Optional[str]


class QueryMedicalConditionsClustersMedicalConditionsResultsWorkflow(BaseModel):
    id: str
    name: str


class QueryMedicalConditionsClustersMedicalConditionsResultsLocation(BaseModel):
    latitude: Optional[float]
    longitude: Optional[float]


class QueryMedicalConditionsClustersMedicalConditionsResultsH3(BaseModel):
    h_3_r_0: Optional[str] = Field(alias="h3r0")
    h_3_r_1: Optional[str] = Field(alias="h3r1")
    h_3_r_2: Optional[str] = Field(alias="h3r2")
    h_3_r_3: Optional[str] = Field(alias="h3r3")
    h_3_r_4: Optional[str] = Field(alias="h3r4")
    h_3_r_5: Optional[str] = Field(alias="h3r5")
    h_3_r_6: Optional[str] = Field(alias="h3r6")
    h_3_r_7: Optional[str] = Field(alias="h3r7")
    h_3_r_8: Optional[str] = Field(alias="h3r8")
    h_3_r_9: Optional[str] = Field(alias="h3r9")
    h_3_r_10: Optional[str] = Field(alias="h3r10")
    h_3_r_11: Optional[str] = Field(alias="h3r11")
    h_3_r_12: Optional[str] = Field(alias="h3r12")
    h_3_r_13: Optional[str] = Field(alias="h3r13")
    h_3_r_14: Optional[str] = Field(alias="h3r14")
    h_3_r_15: Optional[str] = Field(alias="h3r15")


class QueryMedicalConditionsClustersMedicalConditionsClusters(BaseModel):
    clusters: Optional[
        list["QueryMedicalConditionsClustersMedicalConditionsClustersClusters"]
    ]


class QueryMedicalConditionsClustersMedicalConditionsClustersClusters(BaseModel):
    entities: list[
        "QueryMedicalConditionsClustersMedicalConditionsClustersClustersEntities"
    ]
    similarity: Optional[float]


class QueryMedicalConditionsClustersMedicalConditionsClustersClustersEntities(
    BaseModel
):
    id: str
    name: Optional[str]


QueryMedicalConditionsClusters.model_rebuild()
QueryMedicalConditionsClustersMedicalConditions.model_rebuild()
QueryMedicalConditionsClustersMedicalConditionsResults.model_rebuild()
QueryMedicalConditionsClustersMedicalConditionsClusters.model_rebuild()
QueryMedicalConditionsClustersMedicalConditionsClustersClusters.model_rebuild()
