# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ConnectorTypes,
    ContentTypes,
    ConversationTypes,
    EntityOwners,
    EntityState,
    EntityTypes,
    FileTypes,
    FilterMode,
    ObservableTypes,
    ReplicaArtifactTypes,
    ReplicaBranchTypes,
    TimedPolicyRecurrenceTypes,
)


class QueryReplicas(BaseModel):
    replicas: Optional["QueryReplicasReplicas"]


class QueryReplicasReplicas(BaseModel):
    results: Optional[list["QueryReplicasReplicasResults"]]


class QueryReplicasReplicasResults(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    relevance: Optional[float]
    owner: "QueryReplicasReplicasResultsOwner"
    state: EntityState
    type: Optional[EntityTypes]
    content: Optional["QueryReplicasReplicasResultsContent"]
    conversation: Optional["QueryReplicasReplicasResultsConversation"]
    skill: Optional["QueryReplicasReplicasResultsSkill"]
    git: Optional["QueryReplicasReplicasResultsGit"]
    connector: "QueryReplicasReplicasResultsConnector"
    marker_slug: Optional[str] = Field(alias="markerSlug")
    artifact_types: Optional[list[Optional[ReplicaArtifactTypes]]] = Field(
        alias="artifactTypes"
    )
    synchronize_deletes: Optional[bool] = Field(alias="synchronizeDeletes")
    commit_message: Optional[str] = Field(alias="commitMessage")
    schedule_policy: Optional["QueryReplicasReplicasResultsSchedulePolicy"] = Field(
        alias="schedulePolicy"
    )
    last_reconcile_date: Optional[Any] = Field(alias="lastReconcileDate")
    next_reconcile_date: Optional[Any] = Field(alias="nextReconcileDate")
    last_replica_date: Optional[Any] = Field(alias="lastReplicaDate")
    last_revision_id: Optional[str] = Field(alias="lastRevisionId")
    last_revision_uri: Optional[str] = Field(alias="lastRevisionUri")
    last_error_code: Optional[str] = Field(alias="lastErrorCode")
    last_error_message: Optional[str] = Field(alias="lastErrorMessage")
    last_file_upsert_count: Optional[int] = Field(alias="lastFileUpsertCount")
    last_file_delete_count: Optional[int] = Field(alias="lastFileDeleteCount")
    last_file_skip_count: Optional[int] = Field(alias="lastFileSkipCount")
    last_file_unchanged_count: Optional[int] = Field(alias="lastFileUnchangedCount")


class QueryReplicasReplicasResultsOwner(BaseModel):
    id: str


class QueryReplicasReplicasResultsContent(BaseModel):
    filter: Optional["QueryReplicasReplicasResultsContentFilter"]


class QueryReplicasReplicasResultsContentFilter(BaseModel):
    date_range: Optional["QueryReplicasReplicasResultsContentFilterDateRange"] = Field(
        alias="dateRange"
    )
    in_last: Optional[Any] = Field(alias="inLast")
    in_next: Optional[Any] = Field(alias="inNext")
    creation_date_range: Optional[
        "QueryReplicasReplicasResultsContentFilterCreationDateRange"
    ] = Field(alias="creationDateRange")
    created_in_last: Optional[Any] = Field(alias="createdInLast")
    types: Optional[list[ContentTypes]]
    file_types: Optional[list[FileTypes]] = Field(alias="fileTypes")
    formats: Optional[list[str]]
    file_extensions: Optional[list[str]] = Field(alias="fileExtensions")
    file_size_range: Optional[
        "QueryReplicasReplicasResultsContentFilterFileSizeRange"
    ] = Field(alias="fileSizeRange")
    similar_contents: Optional[
        list["QueryReplicasReplicasResultsContentFilterSimilarContents"]
    ] = Field(alias="similarContents")
    contents: Optional[list["QueryReplicasReplicasResultsContentFilterContents"]]
    feeds: Optional[list["QueryReplicasReplicasResultsContentFilterFeeds"]]
    workflows: Optional[list["QueryReplicasReplicasResultsContentFilterWorkflows"]]
    collections: Optional[list["QueryReplicasReplicasResultsContentFilterCollections"]]
    users: Optional[list["QueryReplicasReplicasResultsContentFilterUsers"]]
    observations: Optional[
        list["QueryReplicasReplicasResultsContentFilterObservations"]
    ]
    or_: Optional[list["QueryReplicasReplicasResultsContentFilterOr"]] = Field(
        alias="or"
    )
    and_: Optional[list["QueryReplicasReplicasResultsContentFilterAnd"]] = Field(
        alias="and"
    )
    has_observations: Optional[bool] = Field(alias="hasObservations")
    has_feeds: Optional[bool] = Field(alias="hasFeeds")
    has_collections: Optional[bool] = Field(alias="hasCollections")
    has_workflows: Optional[bool] = Field(alias="hasWorkflows")
    collection_mode: Optional[FilterMode] = Field(alias="collectionMode")
    observation_mode: Optional[FilterMode] = Field(alias="observationMode")


class QueryReplicasReplicasResultsContentFilterDateRange(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class QueryReplicasReplicasResultsContentFilterCreationDateRange(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class QueryReplicasReplicasResultsContentFilterFileSizeRange(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class QueryReplicasReplicasResultsContentFilterSimilarContents(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterContents(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterFeeds(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterWorkflows(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterCollections(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterUsers(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterObservations(BaseModel):
    type: ObservableTypes
    observable: "QueryReplicasReplicasResultsContentFilterObservationsObservable"
    states: Optional[list[EntityState]]


class QueryReplicasReplicasResultsContentFilterObservationsObservable(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterOr(BaseModel):
    feeds: Optional[list["QueryReplicasReplicasResultsContentFilterOrFeeds"]]
    workflows: Optional[list["QueryReplicasReplicasResultsContentFilterOrWorkflows"]]
    collections: Optional[
        list["QueryReplicasReplicasResultsContentFilterOrCollections"]
    ]
    users: Optional[list["QueryReplicasReplicasResultsContentFilterOrUsers"]]
    observations: Optional[
        list["QueryReplicasReplicasResultsContentFilterOrObservations"]
    ]


class QueryReplicasReplicasResultsContentFilterOrFeeds(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterOrWorkflows(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterOrCollections(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterOrUsers(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterOrObservations(BaseModel):
    type: ObservableTypes
    observable: "QueryReplicasReplicasResultsContentFilterOrObservationsObservable"
    states: Optional[list[EntityState]]


class QueryReplicasReplicasResultsContentFilterOrObservationsObservable(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterAnd(BaseModel):
    feeds: Optional[list["QueryReplicasReplicasResultsContentFilterAndFeeds"]]
    workflows: Optional[list["QueryReplicasReplicasResultsContentFilterAndWorkflows"]]
    collections: Optional[
        list["QueryReplicasReplicasResultsContentFilterAndCollections"]
    ]
    users: Optional[list["QueryReplicasReplicasResultsContentFilterAndUsers"]]
    observations: Optional[
        list["QueryReplicasReplicasResultsContentFilterAndObservations"]
    ]


class QueryReplicasReplicasResultsContentFilterAndFeeds(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterAndWorkflows(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterAndCollections(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterAndUsers(BaseModel):
    id: str


class QueryReplicasReplicasResultsContentFilterAndObservations(BaseModel):
    type: ObservableTypes
    observable: "QueryReplicasReplicasResultsContentFilterAndObservationsObservable"
    states: Optional[list[EntityState]]


class QueryReplicasReplicasResultsContentFilterAndObservationsObservable(BaseModel):
    id: str


class QueryReplicasReplicasResultsConversation(BaseModel):
    filter: Optional["QueryReplicasReplicasResultsConversationFilter"]


class QueryReplicasReplicasResultsConversationFilter(BaseModel):
    types: Optional[list[ConversationTypes]]
    conversations: Optional[
        list["QueryReplicasReplicasResultsConversationFilterConversations"]
    ]
    exclude_conversations: Optional[
        list["QueryReplicasReplicasResultsConversationFilterExcludeConversations"]
    ] = Field(alias="excludeConversations")
    agents: Optional[list["QueryReplicasReplicasResultsConversationFilterAgents"]]
    collections: Optional[
        list["QueryReplicasReplicasResultsConversationFilterCollections"]
    ]
    observations: Optional[
        list["QueryReplicasReplicasResultsConversationFilterObservations"]
    ]
    has_collections: Optional[bool] = Field(alias="hasCollections")
    has_observations: Optional[bool] = Field(alias="hasObservations")
    collection_mode: Optional[FilterMode] = Field(alias="collectionMode")
    observation_mode: Optional[FilterMode] = Field(alias="observationMode")


class QueryReplicasReplicasResultsConversationFilterConversations(BaseModel):
    id: str


class QueryReplicasReplicasResultsConversationFilterExcludeConversations(BaseModel):
    id: str


class QueryReplicasReplicasResultsConversationFilterAgents(BaseModel):
    id: str


class QueryReplicasReplicasResultsConversationFilterCollections(BaseModel):
    id: str


class QueryReplicasReplicasResultsConversationFilterObservations(BaseModel):
    type: ObservableTypes
    observable: "QueryReplicasReplicasResultsConversationFilterObservationsObservable"
    states: Optional[list[EntityState]]


class QueryReplicasReplicasResultsConversationFilterObservationsObservable(BaseModel):
    id: str


class QueryReplicasReplicasResultsSkill(BaseModel):
    filter: Optional["QueryReplicasReplicasResultsSkillFilter"]


class QueryReplicasReplicasResultsSkillFilter(BaseModel):
    skill_owners: Optional[list[EntityOwners]] = Field(alias="skillOwners")
    skills: Optional[list["QueryReplicasReplicasResultsSkillFilterSkills"]]
    exclude_skills: Optional[
        list["QueryReplicasReplicasResultsSkillFilterExcludeSkills"]
    ] = Field(alias="excludeSkills")
    feeds: Optional[list["QueryReplicasReplicasResultsSkillFilterFeeds"]]
    has_feeds: Optional[bool] = Field(alias="hasFeeds")
    collections: Optional[list["QueryReplicasReplicasResultsSkillFilterCollections"]]
    has_collections: Optional[bool] = Field(alias="hasCollections")


class QueryReplicasReplicasResultsSkillFilterSkills(BaseModel):
    id: str


class QueryReplicasReplicasResultsSkillFilterExcludeSkills(BaseModel):
    id: str


class QueryReplicasReplicasResultsSkillFilterFeeds(BaseModel):
    id: str


class QueryReplicasReplicasResultsSkillFilterCollections(BaseModel):
    id: str


class QueryReplicasReplicasResultsGit(BaseModel):
    branch_type: Optional[ReplicaBranchTypes] = Field(alias="branchType")
    branch: Optional[str]
    resolved_branch: Optional[str] = Field(alias="resolvedBranch")
    repository_owner: Optional[str] = Field(alias="repositoryOwner")
    repository_name: Optional[str] = Field(alias="repositoryName")
    project_path: Optional[str] = Field(alias="projectPath")
    target_path: Optional[str] = Field(alias="targetPath")


class QueryReplicasReplicasResultsConnector(BaseModel):
    id: str
    name: str
    state: EntityState
    type: Optional[ConnectorTypes]


class QueryReplicasReplicasResultsSchedulePolicy(BaseModel):
    recurrence_type: Optional[TimedPolicyRecurrenceTypes] = Field(
        alias="recurrenceType"
    )
    repeat_interval: Optional[Any] = Field(alias="repeatInterval")


QueryReplicas.model_rebuild()
QueryReplicasReplicas.model_rebuild()
QueryReplicasReplicasResults.model_rebuild()
QueryReplicasReplicasResultsContent.model_rebuild()
QueryReplicasReplicasResultsContentFilter.model_rebuild()
QueryReplicasReplicasResultsContentFilterObservations.model_rebuild()
QueryReplicasReplicasResultsContentFilterOr.model_rebuild()
QueryReplicasReplicasResultsContentFilterOrObservations.model_rebuild()
QueryReplicasReplicasResultsContentFilterAnd.model_rebuild()
QueryReplicasReplicasResultsContentFilterAndObservations.model_rebuild()
QueryReplicasReplicasResultsConversation.model_rebuild()
QueryReplicasReplicasResultsConversationFilter.model_rebuild()
QueryReplicasReplicasResultsConversationFilterObservations.model_rebuild()
QueryReplicasReplicasResultsSkill.model_rebuild()
QueryReplicasReplicasResultsSkillFilter.model_rebuild()
