# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState, LinkTypes


class QueryMedicalIndications(BaseModel):
    medical_indications: Optional["QueryMedicalIndicationsMedicalIndications"] = Field(
        alias="medicalIndications"
    )


class QueryMedicalIndicationsMedicalIndications(BaseModel):
    results: Optional[
        List[Optional["QueryMedicalIndicationsMedicalIndicationsResults"]]
    ]


class QueryMedicalIndicationsMedicalIndicationsResults(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    relevance: Optional[float]
    owner: "QueryMedicalIndicationsMedicalIndicationsResultsOwner"
    state: EntityState
    alternate_names: Optional[List[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[
        List[Optional["QueryMedicalIndicationsMedicalIndicationsResultsFeeds"]]
    ]
    links: Optional[
        List[Optional["QueryMedicalIndicationsMedicalIndicationsResultsLinks"]]
    ]
    workflow: Optional["QueryMedicalIndicationsMedicalIndicationsResultsWorkflow"]


class QueryMedicalIndicationsMedicalIndicationsResultsOwner(BaseModel):
    id: str


class QueryMedicalIndicationsMedicalIndicationsResultsFeeds(BaseModel):
    id: str
    name: str


class QueryMedicalIndicationsMedicalIndicationsResultsLinks(BaseModel):
    uri: Optional[Any]
    link_type: Optional[LinkTypes] = Field(alias="linkType")
    excerpts: Optional[str]


class QueryMedicalIndicationsMedicalIndicationsResultsWorkflow(BaseModel):
    id: str
    name: str


QueryMedicalIndications.model_rebuild()
QueryMedicalIndicationsMedicalIndications.model_rebuild()
QueryMedicalIndicationsMedicalIndicationsResults.model_rebuild()
