# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, List, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState, LinkTypes


class QueryRepos(BaseModel):
    repos: Optional["QueryReposRepos"]


class QueryReposRepos(BaseModel):
    results: Optional[List[Optional["QueryReposReposResults"]]]


class QueryReposReposResults(BaseModel):
    id: str
    name: str
    creation_date: Any = Field(alias="creationDate")
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    relevance: Optional[float]
    owner: "QueryReposReposResultsOwner"
    state: EntityState
    alternate_names: Optional[List[Optional[str]]] = Field(alias="alternateNames")
    uri: Optional[Any]
    description: Optional[str]
    identifier: Optional[str]
    thing: Optional[str]
    feeds: Optional[List[Optional["QueryReposReposResultsFeeds"]]]
    links: Optional[List[Optional["QueryReposReposResultsLinks"]]]
    workflow: Optional["QueryReposReposResultsWorkflow"]


class QueryReposReposResultsOwner(BaseModel):
    id: str


class QueryReposReposResultsFeeds(BaseModel):
    id: str
    name: str


class QueryReposReposResultsLinks(BaseModel):
    uri: Optional[Any]
    link_type: Optional[LinkTypes] = Field(alias="linkType")
    excerpts: Optional[str]


class QueryReposReposResultsWorkflow(BaseModel):
    id: str
    name: str


QueryRepos.model_rebuild()
QueryReposRepos.model_rebuild()
QueryReposReposResults.model_rebuild()
