# Generated by ariadne-codegen
# Source: ./documents

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryJiraIssueTypes(BaseModel):
    jira_issue_types: Optional["QueryJiraIssueTypesJiraIssueTypes"] = Field(
        alias="jiraIssueTypes"
    )


class QueryJiraIssueTypesJiraIssueTypes(BaseModel):
    results: Optional[list[Optional["QueryJiraIssueTypesJiraIssueTypesResults"]]]


class QueryJiraIssueTypesJiraIssueTypesResults(BaseModel):
    id: Optional[str]
    name: Optional[str]
    description: Optional[str]


QueryJiraIssueTypes.model_rebuild()
QueryJiraIssueTypesJiraIssueTypes.model_rebuild()
