# Generated by ariadne-codegen
# Source: ./documents

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class QueryGoogleDriveFolders(BaseModel):
    google_drive_folders: Optional["QueryGoogleDriveFoldersGoogleDriveFolders"] = Field(
        alias="googleDriveFolders"
    )


class QueryGoogleDriveFoldersGoogleDriveFolders(BaseModel):
    results: Optional[
        list[Optional["QueryGoogleDriveFoldersGoogleDriveFoldersResults"]]
    ]


class QueryGoogleDriveFoldersGoogleDriveFoldersResults(BaseModel):
    folder_name: Optional[str] = Field(alias="folderName")
    folder_id: Optional[str] = Field(alias="folderId")
    folder_path: Optional[str] = Field(alias="folderPath")


QueryGoogleDriveFolders.model_rebuild()
QueryGoogleDriveFoldersGoogleDriveFolders.model_rebuild()
