# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import DistributionServiceTypes


class Read(BaseModel):
    read: Optional["ReadRead"]


class ReadRead(BaseModel):
    identifier: Optional[str]
    name: Optional[str]
    markdown: Optional[str]
    uri: Optional[str]
    modified_date: Optional[Any] = Field(alias="modifiedDate")
    service_type: Optional[DistributionServiceTypes] = Field(alias="serviceType")


Read.model_rebuild()
