# Generated by ariadne-codegen
# Source: ./documents

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import EntityState, FeedSyncMode, FeedTypes


class UpdateFeed(BaseModel):
    update_feed: Optional["UpdateFeedUpdateFeed"] = Field(alias="updateFeed")


class UpdateFeedUpdateFeed(BaseModel):
    id: str
    name: str
    state: EntityState
    type: FeedTypes
    sync_mode: Optional[FeedSyncMode] = Field(alias="syncMode")


UpdateFeed.model_rebuild()
