# Generated by ariadne-codegen
# Source: ./documents

from typing import Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import AgentModes, AgentTypes, EntityState


class UpdateAgentScratchpad(BaseModel):
    update_agent_scratchpad: Optional["UpdateAgentScratchpadUpdateAgentScratchpad"] = (
        Field(alias="updateAgentScratchpad")
    )


class UpdateAgentScratchpadUpdateAgentScratchpad(BaseModel):
    id: str
    name: str
    state: EntityState
    type: AgentTypes
    mode: AgentModes


UpdateAgentScratchpad.model_rebuild()
