# Generated by ariadne-codegen
# Source: ./documents

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    ConnectorTypes,
    ContentTypes,
    ConversationTypes,
    EntityOwners,
    EntityState,
    EntityTypes,
    FileTypes,
    FilterMode,
    ObservableTypes,
    ReplicaArtifactTypes,
    ReplicaBranchTypes,
    TimedPolicyRecurrenceTypes,
)


class UpsertReplica(BaseModel):
    upsert_replica: Optional["UpsertReplicaUpsertReplica"] = Field(
        alias="upsertReplica"
    )


class UpsertReplicaUpsertReplica(BaseModel):
    id: str
    name: str
    state: EntityState
    type: Optional[EntityTypes]
    content: Optional["UpsertReplicaUpsertReplicaContent"]
    conversation: Optional["UpsertReplicaUpsertReplicaConversation"]
    skill: Optional["UpsertReplicaUpsertReplicaSkill"]
    git: Optional["UpsertReplicaUpsertReplicaGit"]
    connector: "UpsertReplicaUpsertReplicaConnector"
    marker_slug: Optional[str] = Field(alias="markerSlug")
    artifact_types: Optional[list[Optional[ReplicaArtifactTypes]]] = Field(
        alias="artifactTypes"
    )
    synchronize_deletes: Optional[bool] = Field(alias="synchronizeDeletes")
    commit_message: Optional[str] = Field(alias="commitMessage")
    schedule_policy: Optional["UpsertReplicaUpsertReplicaSchedulePolicy"] = Field(
        alias="schedulePolicy"
    )
    last_reconcile_date: Optional[Any] = Field(alias="lastReconcileDate")
    next_reconcile_date: Optional[Any] = Field(alias="nextReconcileDate")
    last_replica_date: Optional[Any] = Field(alias="lastReplicaDate")
    last_revision_id: Optional[str] = Field(alias="lastRevisionId")
    last_revision_uri: Optional[str] = Field(alias="lastRevisionUri")
    last_error_code: Optional[str] = Field(alias="lastErrorCode")
    last_error_message: Optional[str] = Field(alias="lastErrorMessage")
    last_file_upsert_count: Optional[int] = Field(alias="lastFileUpsertCount")
    last_file_delete_count: Optional[int] = Field(alias="lastFileDeleteCount")
    last_file_skip_count: Optional[int] = Field(alias="lastFileSkipCount")
    last_file_unchanged_count: Optional[int] = Field(alias="lastFileUnchangedCount")


class UpsertReplicaUpsertReplicaContent(BaseModel):
    filter: Optional["UpsertReplicaUpsertReplicaContentFilter"]


class UpsertReplicaUpsertReplicaContentFilter(BaseModel):
    date_range: Optional["UpsertReplicaUpsertReplicaContentFilterDateRange"] = Field(
        alias="dateRange"
    )
    in_last: Optional[Any] = Field(alias="inLast")
    in_next: Optional[Any] = Field(alias="inNext")
    creation_date_range: Optional[
        "UpsertReplicaUpsertReplicaContentFilterCreationDateRange"
    ] = Field(alias="creationDateRange")
    created_in_last: Optional[Any] = Field(alias="createdInLast")
    types: Optional[list[ContentTypes]]
    file_types: Optional[list[FileTypes]] = Field(alias="fileTypes")
    formats: Optional[list[str]]
    file_extensions: Optional[list[str]] = Field(alias="fileExtensions")
    file_size_range: Optional[
        "UpsertReplicaUpsertReplicaContentFilterFileSizeRange"
    ] = Field(alias="fileSizeRange")
    similar_contents: Optional[
        list["UpsertReplicaUpsertReplicaContentFilterSimilarContents"]
    ] = Field(alias="similarContents")
    contents: Optional[list["UpsertReplicaUpsertReplicaContentFilterContents"]]
    feeds: Optional[list["UpsertReplicaUpsertReplicaContentFilterFeeds"]]
    workflows: Optional[list["UpsertReplicaUpsertReplicaContentFilterWorkflows"]]
    collections: Optional[list["UpsertReplicaUpsertReplicaContentFilterCollections"]]
    users: Optional[list["UpsertReplicaUpsertReplicaContentFilterUsers"]]
    observations: Optional[list["UpsertReplicaUpsertReplicaContentFilterObservations"]]
    or_: Optional[list["UpsertReplicaUpsertReplicaContentFilterOr"]] = Field(alias="or")
    and_: Optional[list["UpsertReplicaUpsertReplicaContentFilterAnd"]] = Field(
        alias="and"
    )
    has_observations: Optional[bool] = Field(alias="hasObservations")
    has_feeds: Optional[bool] = Field(alias="hasFeeds")
    has_collections: Optional[bool] = Field(alias="hasCollections")
    has_workflows: Optional[bool] = Field(alias="hasWorkflows")
    collection_mode: Optional[FilterMode] = Field(alias="collectionMode")
    observation_mode: Optional[FilterMode] = Field(alias="observationMode")


class UpsertReplicaUpsertReplicaContentFilterDateRange(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class UpsertReplicaUpsertReplicaContentFilterCreationDateRange(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class UpsertReplicaUpsertReplicaContentFilterFileSizeRange(BaseModel):
    from_: Optional[Any] = Field(alias="from")
    to: Optional[Any]


class UpsertReplicaUpsertReplicaContentFilterSimilarContents(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterContents(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterFeeds(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterWorkflows(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterCollections(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterUsers(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterObservations(BaseModel):
    type: ObservableTypes
    observable: "UpsertReplicaUpsertReplicaContentFilterObservationsObservable"
    states: Optional[list[EntityState]]


class UpsertReplicaUpsertReplicaContentFilterObservationsObservable(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterOr(BaseModel):
    feeds: Optional[list["UpsertReplicaUpsertReplicaContentFilterOrFeeds"]]
    workflows: Optional[list["UpsertReplicaUpsertReplicaContentFilterOrWorkflows"]]
    collections: Optional[list["UpsertReplicaUpsertReplicaContentFilterOrCollections"]]
    users: Optional[list["UpsertReplicaUpsertReplicaContentFilterOrUsers"]]
    observations: Optional[
        list["UpsertReplicaUpsertReplicaContentFilterOrObservations"]
    ]


class UpsertReplicaUpsertReplicaContentFilterOrFeeds(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterOrWorkflows(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterOrCollections(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterOrUsers(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterOrObservations(BaseModel):
    type: ObservableTypes
    observable: "UpsertReplicaUpsertReplicaContentFilterOrObservationsObservable"
    states: Optional[list[EntityState]]


class UpsertReplicaUpsertReplicaContentFilterOrObservationsObservable(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterAnd(BaseModel):
    feeds: Optional[list["UpsertReplicaUpsertReplicaContentFilterAndFeeds"]]
    workflows: Optional[list["UpsertReplicaUpsertReplicaContentFilterAndWorkflows"]]
    collections: Optional[list["UpsertReplicaUpsertReplicaContentFilterAndCollections"]]
    users: Optional[list["UpsertReplicaUpsertReplicaContentFilterAndUsers"]]
    observations: Optional[
        list["UpsertReplicaUpsertReplicaContentFilterAndObservations"]
    ]


class UpsertReplicaUpsertReplicaContentFilterAndFeeds(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterAndWorkflows(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterAndCollections(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterAndUsers(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaContentFilterAndObservations(BaseModel):
    type: ObservableTypes
    observable: "UpsertReplicaUpsertReplicaContentFilterAndObservationsObservable"
    states: Optional[list[EntityState]]


class UpsertReplicaUpsertReplicaContentFilterAndObservationsObservable(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaConversation(BaseModel):
    filter: Optional["UpsertReplicaUpsertReplicaConversationFilter"]


class UpsertReplicaUpsertReplicaConversationFilter(BaseModel):
    types: Optional[list[ConversationTypes]]
    conversations: Optional[
        list["UpsertReplicaUpsertReplicaConversationFilterConversations"]
    ]
    exclude_conversations: Optional[
        list["UpsertReplicaUpsertReplicaConversationFilterExcludeConversations"]
    ] = Field(alias="excludeConversations")
    agents: Optional[list["UpsertReplicaUpsertReplicaConversationFilterAgents"]]
    collections: Optional[
        list["UpsertReplicaUpsertReplicaConversationFilterCollections"]
    ]
    observations: Optional[
        list["UpsertReplicaUpsertReplicaConversationFilterObservations"]
    ]
    has_collections: Optional[bool] = Field(alias="hasCollections")
    has_observations: Optional[bool] = Field(alias="hasObservations")
    collection_mode: Optional[FilterMode] = Field(alias="collectionMode")
    observation_mode: Optional[FilterMode] = Field(alias="observationMode")


class UpsertReplicaUpsertReplicaConversationFilterConversations(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaConversationFilterExcludeConversations(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaConversationFilterAgents(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaConversationFilterCollections(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaConversationFilterObservations(BaseModel):
    type: ObservableTypes
    observable: "UpsertReplicaUpsertReplicaConversationFilterObservationsObservable"
    states: Optional[list[EntityState]]


class UpsertReplicaUpsertReplicaConversationFilterObservationsObservable(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaSkill(BaseModel):
    filter: Optional["UpsertReplicaUpsertReplicaSkillFilter"]


class UpsertReplicaUpsertReplicaSkillFilter(BaseModel):
    skill_owners: Optional[list[EntityOwners]] = Field(alias="skillOwners")
    skills: Optional[list["UpsertReplicaUpsertReplicaSkillFilterSkills"]]
    exclude_skills: Optional[
        list["UpsertReplicaUpsertReplicaSkillFilterExcludeSkills"]
    ] = Field(alias="excludeSkills")
    feeds: Optional[list["UpsertReplicaUpsertReplicaSkillFilterFeeds"]]
    has_feeds: Optional[bool] = Field(alias="hasFeeds")
    collections: Optional[list["UpsertReplicaUpsertReplicaSkillFilterCollections"]]
    has_collections: Optional[bool] = Field(alias="hasCollections")


class UpsertReplicaUpsertReplicaSkillFilterSkills(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaSkillFilterExcludeSkills(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaSkillFilterFeeds(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaSkillFilterCollections(BaseModel):
    id: str


class UpsertReplicaUpsertReplicaGit(BaseModel):
    branch_type: Optional[ReplicaBranchTypes] = Field(alias="branchType")
    branch: Optional[str]
    resolved_branch: Optional[str] = Field(alias="resolvedBranch")
    repository_owner: Optional[str] = Field(alias="repositoryOwner")
    repository_name: Optional[str] = Field(alias="repositoryName")
    project_path: Optional[str] = Field(alias="projectPath")
    target_path: Optional[str] = Field(alias="targetPath")


class UpsertReplicaUpsertReplicaConnector(BaseModel):
    id: str
    name: str
    state: EntityState
    type: Optional[ConnectorTypes]


class UpsertReplicaUpsertReplicaSchedulePolicy(BaseModel):
    recurrence_type: Optional[TimedPolicyRecurrenceTypes] = Field(
        alias="recurrenceType"
    )
    repeat_interval: Optional[Any] = Field(alias="repeatInterval")


UpsertReplica.model_rebuild()
UpsertReplicaUpsertReplica.model_rebuild()
UpsertReplicaUpsertReplicaContent.model_rebuild()
UpsertReplicaUpsertReplicaContentFilter.model_rebuild()
UpsertReplicaUpsertReplicaContentFilterObservations.model_rebuild()
UpsertReplicaUpsertReplicaContentFilterOr.model_rebuild()
UpsertReplicaUpsertReplicaContentFilterOrObservations.model_rebuild()
UpsertReplicaUpsertReplicaContentFilterAnd.model_rebuild()
UpsertReplicaUpsertReplicaContentFilterAndObservations.model_rebuild()
UpsertReplicaUpsertReplicaConversation.model_rebuild()
UpsertReplicaUpsertReplicaConversationFilter.model_rebuild()
UpsertReplicaUpsertReplicaConversationFilterObservations.model_rebuild()
UpsertReplicaUpsertReplicaSkill.model_rebuild()
UpsertReplicaUpsertReplicaSkillFilter.model_rebuild()
