trigger:
  branches:
    include:
      - main

name: $(Date:yyyyMMdd)$(Rev:rrr)

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x"
      addToPath: true

  - script: |
      echo "##vso[task.setvariable variable=PACKAGE_VERSION]1.0.$(Build.BuildNumber)"
    displayName: "Set package version"

  - script: |
      python -m pip install --upgrade pip
      pip install setuptools wheel twine
      python setup.py sdist bdist_wheel
    displayName: "Install dependencies and build"

  - script: |
      twine upload dist/* -u __token__ -p $(PYPI_TOKEN) --skip-existing
    displayName: "Upload to PyPI"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
